# Generated by Django 5.0.3 on 2024-03-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_special', models.CharField(max_length=100)),
                ('doctor_img', models.ImageField(upload_to='doctors')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Mobile_No', models.CharField(max_length=100)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Booking_Date', models.DateField()),
                ('Booking_Time', models.TimeField()),
                ('Booking_On', models.DateField(auto_now_add=True)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctors')),
            ],
        ),
    ]
